insert into user(id,username,email, authorities) values(1,'gmastro','mastronardi.gonzalo@gmail.com', 'ROLE_MEDICO');
insert into user(id,username,email, authorities) values(2,'mbosn','iriarte.marcos@gmail.com', 'ROLE_MEDICO');
insert into user(id,username,email, authorities) values(3,'mbutti','matias.butti@gmail.com', 'ROLE_MEDICO');
insert into user(id,username,email, authorities) values(4,'mbecca','beccariamatias@gmail.com', 'ROLE_MEDICO');

/* INGRESO DE PACIENTES*/

INSERT INTO INGRESO_PACIENTE (ANTECEDENTES_ENFERMEDAD, ANTECEDENTES_PERSONALES, ENFERMEDAD_ACTUAL, EXAMEN_FISICO, FECHA_INGRESO, MOTIVO_CONSULTA, DIAGNOSTICO_PRESUNTIVO_ID, DIAGNOSTICO_SINTOMATICO_ID)  VALUES ('antecedentes_enf', 'antecedentes_pers', 'enf_act', 'examen_fisico', '2018-10-09 12:38:47.767', 'motivo', 1,1)
INSERT INTO INGRESO_PACIENTE (ANTECEDENTES_ENFERMEDAD, ANTECEDENTES_PERSONALES, ENFERMEDAD_ACTUAL, EXAMEN_FISICO, FECHA_INGRESO, MOTIVO_CONSULTA, DIAGNOSTICO_PRESUNTIVO_ID, DIAGNOSTICO_SINTOMATICO_ID)  VALUES ('antecedentes_enf', 'antecedentes_pers', 'enf_act', 'examen_fisico', '2018-11-09 12:38:47.767', 'motivo', 1,1)
INSERT INTO INGRESO_PACIENTE (ANTECEDENTES_ENFERMEDAD, ANTECEDENTES_PERSONALES, ENFERMEDAD_ACTUAL, EXAMEN_FISICO, FECHA_INGRESO, MOTIVO_CONSULTA, DIAGNOSTICO_PRESUNTIVO_ID, DIAGNOSTICO_SINTOMATICO_ID)  VALUES ('antecedentes_enf', 'antecedentes_pers', 'enf_act', 'examen_fisico', '2018-09-09 12:38:47.767', 'motivo', 1,1)
INSERT INTO INGRESO_PACIENTE (ANTECEDENTES_ENFERMEDAD, ANTECEDENTES_PERSONALES, ENFERMEDAD_ACTUAL, EXAMEN_FISICO, FECHA_INGRESO, MOTIVO_CONSULTA, DIAGNOSTICO_PRESUNTIVO_ID, DIAGNOSTICO_SINTOMATICO_ID)  VALUES ('antecedentes_enf', 'antecedentes_pers', 'enf_act', 'examen_fisico', '2018-08-09 12:38:47.767', 'motivo', 1,1)
INSERT INTO INGRESO_PACIENTE (ANTECEDENTES_ENFERMEDAD, ANTECEDENTES_PERSONALES, ENFERMEDAD_ACTUAL, EXAMEN_FISICO, FECHA_INGRESO, MOTIVO_CONSULTA, DIAGNOSTICO_PRESUNTIVO_ID, DIAGNOSTICO_SINTOMATICO_ID)  VALUES ('antecedentes_enf', 'antecedentes_pers', 'enf_act', 'examen_fisico', '2018-07-09 12:38:47.767', 'motivo', 1,1)
INSERT INTO INGRESO_PACIENTE (ANTECEDENTES_ENFERMEDAD, ANTECEDENTES_PERSONALES, ENFERMEDAD_ACTUAL, EXAMEN_FISICO, FECHA_INGRESO, MOTIVO_CONSULTA, DIAGNOSTICO_PRESUNTIVO_ID, DIAGNOSTICO_SINTOMATICO_ID)  VALUES ('antecedentes_enf', 'antecedentes_pers', 'enf_act', 'examen_fisico', '2018-06-09 12:38:47.767', 'motivo', 1,1)
INSERT INTO INGRESO_PACIENTE (ANTECEDENTES_ENFERMEDAD, ANTECEDENTES_PERSONALES, ENFERMEDAD_ACTUAL, EXAMEN_FISICO, FECHA_INGRESO, MOTIVO_CONSULTA, DIAGNOSTICO_PRESUNTIVO_ID, DIAGNOSTICO_SINTOMATICO_ID)  VALUES ('antecedentes_enf', 'antecedentes_pers', 'enf_act', 'examen_fisico', '2018-05-09 12:38:47.767', 'motivo', 1,1)
INSERT INTO INGRESO_PACIENTE (ANTECEDENTES_ENFERMEDAD, ANTECEDENTES_PERSONALES, ENFERMEDAD_ACTUAL, EXAMEN_FISICO, FECHA_INGRESO, MOTIVO_CONSULTA, DIAGNOSTICO_PRESUNTIVO_ID, DIAGNOSTICO_SINTOMATICO_ID)  VALUES ('antecedentes_enf', 'antecedentes_pers', 'enf_act', 'examen_fisico', '2018-04-09 12:38:47.767', 'motivo', 1,1)
INSERT INTO INGRESO_PACIENTE (ANTECEDENTES_ENFERMEDAD, ANTECEDENTES_PERSONALES, ENFERMEDAD_ACTUAL, EXAMEN_FISICO, FECHA_INGRESO, MOTIVO_CONSULTA, DIAGNOSTICO_PRESUNTIVO_ID, DIAGNOSTICO_SINTOMATICO_ID)  VALUES ('antecedentes_enf', 'antecedentes_pers', 'enf_act', 'examen_fisico', '2018-03-09 12:38:47.767', 'motivo', 1,1)
INSERT INTO INGRESO_PACIENTE (ANTECEDENTES_ENFERMEDAD, ANTECEDENTES_PERSONALES, ENFERMEDAD_ACTUAL, EXAMEN_FISICO, FECHA_INGRESO, MOTIVO_CONSULTA, DIAGNOSTICO_PRESUNTIVO_ID, DIAGNOSTICO_SINTOMATICO_ID)  VALUES ('antecedentes_enf', 'antecedentes_pers', 'enf_act', 'examen_fisico', '2018-02-09 12:38:47.767', 'motivo', 1,1)



